# 파일 규격 버전
version: "3.8"

# 실행하려는 컨테이너들 정의
services:
  # 서비스명
  redis_container:
    # 사용할 이미지
    image: redis:latest
    # 컨테이너명
    container_name: redis_test
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --protected-mode no --bind 0.0.0.0
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-calendars-container
    volumes:
      - ./config/prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      calendars_network:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-calendars-local
    ports:
      - "3535:3000"
    networks:
      calendars_network:
  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://host.docker.internal:6379
    ports:
      - 9121:9121
    restart: always
    networks:
      calendars_network:
networks:
  calendars_network:
    driver: bridge